In [82]:
import pandas as pd
import numpy as np

train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')
weather = pd.read_csv('data/weather.csv')
spray = pd.read_csv('data/spray.csv')

In [83]:
#creating columns with airport coords
train['lat_mid'] = 41.786839 
train['long_mid'] = -87.752090
train['lat_ohare'] = 41.972582
train['long_ohare'] = -87.908753

In [84]:
#using the vincenty method to determine distance in miles between locations and airports
from geopy.distance import vincenty
train['mid']=train.apply(lambda x: vincenty((x['Latitude'], x['Longitude']), (x['lat_mid'], x['long_mid'] )).miles, axis=1)
train['ohare']=train.apply(lambda x: vincenty((x['Latitude'], x['Longitude']), (x['lat_ohare'], x['long_ohare'] )).miles, axis=1)

In [85]:
#Label each entry with its closest airport 'Station'
train.ix[train['mid'] > train['ohare'], 'Station'] = 1 #map 1 to closer if Ohare is closer
train.ix[train['mid'] < train['ohare'], 'Station'] = 2 #map 2 if closer to Midway
train.Station = train.Station.astype(int) #convert from float to int

In [86]:
#fixing missing values in weather dataframe
weather.replace('M',np.NaN, inplace=True) #replace 'M' with 'NaN'
weather.replace('-',np.NaN, inplace=True)
weather.replace('  T', .005, inplace=True)
weather.fillna(method='ffill', inplace=True) #fill in 'NaN' values with those from above it

In [87]:
weather1.corr()

,Station,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Sunrise,Sunset,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
Station,1.000000,0.016332,0.103995,0.058478,0.000000,0.007511,0.029012,-0.035826,0.066112,0.000000,0.000000,0.000000,-0.008428,0.190953,-0.028677,-0.007368,-0.016035,0.002635
Tmax,0.016332,1.000000,0.859981,0.965889,0.681827,0.801733,0.904683,-0.857467,0.832785,-0.488480,0.554672,-0.077527,0.038240,-0.156455,-0.208441,-0.180596,0.029231,-0.167579
Tmin,0.103995,0.859981,1.000000,0.959445,0.573208,0.904358,0.951490,-0.819030,0.859142,-0.470742,0.562221,-0.072669,0.106568,-0.202367,-0.282134,-0.114755,-0.014283,-0.101168
Tavg,0.058478,0.965889,0.959445,1.000000,0.653792,0.882718,0.961982,-0.871441,0.878103,-0.498133,0.579735,-0.077811,0.073636,-0.185066,-0.252536,-0.156094,0.009004,-0.142135
Depart,0.000000,0.681827,0.573208,0.653792,1.000000,0.544273,0.605109,-0.517022,0.625524,-0.027728,0.027630,-0.036936,0.063036,-0.261535,-0.285567,0.010059,0.099266,0.038200
DewPoint,0.007511,0.801733,0.904358,0.882718,0.544273,1.000000,0.972370,-0.773914,0.770554,-0.387249,0.475837,-0.073228,0.232245,-0.303376,-0.353450,-0.189207,0.003466,-0.153916
WetBulb,0.029012,0.904683,0.951490,0.961982,0.605109,0.972370,1.000000,-0.847898,0.835367,-0.456548,0.544595,-0.081433,0.164775,-0.252451,-0.311141,-0.181627,0.004677,-0.159097
Heat,-0.035826,-0.857467,-0.819030,-0.871441,-0.517022,-0.773914,-0.847898,1.000000,-0.530525,0.493845,-0.554089,0.112053,-0.064769,0.163868,0.217284,0.204698,0.080223,0.198175
Cool,0.066112,0.832785,0.859142,0.878103,0.625524,0.770554,0.835367,-0.530525,1.000000,-0.379125,0.461381,-0.025166,0.064074,-0.159977,-0.224471,-0.070080,0.093815,-0.052319
Sunrise,0.000000,-0.488480,-0.470742,-0.498133,-0.027728,-0.387249,-0.456548,0.493845,-0.379125,1.000000,-0.971177,0.064263,-0.045588,0.145857,0.185768,0.072641,0.151500,0.038132
Sunset,0.000000,0.554672,0.562221,0.579735,0.027630,0.475837,0.544595,-0.554089,0.461381,-0.971177,1.000000,-0.068779,0.053987,-0.141858,-0.186612,-0.094880,-0.140331,-0.064892
SnowFall,0.000000,-0.077527,-0.072669,-0.077811,-0.036936,-0.073228,-0.081433,0.112053,-0.025166,0.064263,-0.068779,1.000000,0.006379,0.033928,0.034242,0.119782,0.051687,0.127743
PrecipTotal,-0.008428,0.038240,0.106568,0.073636,0.063036,0.232245,0.164775,-0.064769,0.064074,-0.045588,0.053987,0.006379,1.000000,-0.262822,-0.256030,-0.018221,0.045789,0.100164
StnPressure,0.190953,-0.156455,-0.202367,-0.185066,-0.261535,-0.303376,-0.252451,0.163868,-0.159977,0.145857,-0.141858,0.033928,-0.262822,1.000000,0.968297,-0.209307,-0.220106,-0.303087
SeaLevel,-0.028677,-0.208441,-0.282134,-0.252536,-0.285567,-0.353450,-0.311141,0.217284,-0.224471,0.185768,-0.186612,0.034242,-0.256030,0.968297,1.000000,-0.204250,-0.228012,-0.308159
ResultSpeed,-0.007368,-0.180596,-0.114755,-0.156094,0.010059,-0.189207,-0.181627,0.204698,-0.070080,0.072641,-0.094880,0.119782,-0.018221,-0.209307,-0.204250,1.000000,0.096192,0.909781
ResultDir,-0.016035,0.029231,-0.014283,0.009004,0.099266,0.003466,0.004677,0.080223,0.093815,0.151500,-0.140331,0.051687,0.045789,-0.220106,-0.228012,0.096192,1.000000,0.156419
AvgSpeed,0.002635,-0.167579,-0.101168,-0.142135,0.038200,-0.153916,-0.159097,0.198175,-0.052319,0.038132,-0.064892,0.127743,0.100164,-0.303087,-0.308159,0.909781,0.156419,1.000000

In [88]:
weather.dtypes

Station          int64
Date            object
Tmax             int64
Tmin             int64
Tavg            object
Depart          object
DewPoint         int64
WetBulb         object
Heat            object
Cool            object
Sunrise         object
Sunset          object
CodeSum         object
Depth           object
Water1         float64
SnowFall        object
PrecipTotal     object
StnPressure     object
SeaLevel        object
ResultSpeed    float64
ResultDir        int64
AvgSpeed        object
dtype: object

In [89]:
weather[['Tavg', 'Depart', 'WetBulb', 'Heat', 'Cool', 'Sunrise', 'Sunset', 'Depth', 'SnowFall', 'PrecipTotal', 'StnPressure', 'SeaLevel', 'AvgSpeed' ]]=weather[['Tavg', 'Depart', 'WetBulb', 'Heat', 'Cool', 'Sunrise', 'Sunset', 'Depth', 'SnowFall', 'PrecipTotal', 'StnPressure', 'SeaLevel', 'AvgSpeed' ]].astype('float')
#weather.Depart
#weather.WetBulb
#weather.Heat
#weather.Cool
#weather.Sunrise

In [90]:
weather1 = weather.drop(['Water1', 'Depth', 'CodeSum'],axis=1)

In [91]:
weather1.head(10)

,Station,Date,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,Sunrise,Sunset,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
0,1,2007-05-01,83,50,67.0,14.0,51,56.0,0.0,2.0,448.0,1849.0,0.0,0.000,29.10,29.82,1.7,27,9.2
1,2,2007-05-01,84,52,68.0,14.0,51,57.0,0.0,3.0,448.0,1849.0,0.0,0.000,29.18,29.82,2.7,25,9.6
2,1,2007-05-02,59,42,51.0,-3.0,42,47.0,14.0,0.0,447.0,1850.0,0.0,0.000,29.38,30.09,13.0,4,13.4
3,2,2007-05-02,60,43,52.0,-3.0,42,47.0,13.0,0.0,447.0,1850.0,0.0,0.000,29.44,30.08,13.3,2,13.4
4,1,2007-05-03,66,46,56.0,2.0,40,48.0,9.0,0.0,446.0,1851.0,0.0,0.000,29.39,30.12,11.7,7,11.9
5,2,2007-05-03,67,48,58.0,2.0,40,50.0,7.0,0.0,446.0,1851.0,0.0,0.000,29.46,30.12,12.9,6,13.2
6,1,2007-05-04,66,49,58.0,4.0,41,50.0,7.0,0.0,444.0,1852.0,0.0,0.005,29.31,30.05,10.4,8,10.8
7,2,2007-05-04,78,51,58.0,4.0,42,50.0,7.0,0.0,444.0,1852.0,0.0,0.000,29.36,30.04,10.1,7,10.4
8,1,2007-05-05,66,53,60.0,5.0,38,49.0,5.0,0.0,443.0,1853.0,0.0,0.005,29.40,30.10,11.7,7,12.0
9,2,2007-05-05,66,54,60.0,5.0,39,50.0,5.0,0.0,443.0,1853.0,0.0,0.005,29.46,30.09,11.2,7,11.5

In [92]:
#merge train and weather dataframes
#merge based on matching Date and Station and value
train1 = train.merge(weather1, on= ['Date', 'Station'])

In [93]:
train1.head(5)

,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,...,Cool,Sunrise,Sunset,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,9.0,421.0,1917.0,0.0,0.0,29.39,30.11,5.8,18,6.5
1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,...,9.0,421.0,1917.0,0.0,0.0,29.39,30.11,5.8,18,6.5
2,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,...,9.0,421.0,1917.0,0.0,0.0,29.39,30.11,5.8,18,6.5
3,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,9.0,421.0,1917.0,0.0,0.0,29.39,30.11,5.8,18,6.5
4,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,...,9.0,421.0,1917.0,0.0,0.0,29.39,30.11,5.8,18,6.5

In [95]:
train.head(5)

,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,NumMosquitos,WnvPresent,lat_mid,long_mid,lat_ohare,long_ohare,mid,ohare,Station
0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0,41.786839,-87.75209,41.972582,-87.908753,11.855903,5.686557,1
1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0,41.786839,-87.75209,41.972582,-87.908753,11.855903,5.686557,1
2,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,1,0,41.786839,-87.75209,41.972582,-87.908753,14.393228,7.346732,1
3,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,1,0,41.786839,-87.75209,41.972582,-87.908753,13.456605,4.324427,1
4,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,4,0,41.786839,-87.75209,41.972582,-87.908753,13.456605,4.324427,1