In [1]:
# For each location, the dots show the date of each record we have in the data.
# For the training data, this shows us when/where measurements were actually taken.
# But for the test data, we see a very regular set of locations/dates.  
# (This is because the test data has been filled in with many rows that don't always correspond to real measurements. 
# We need to make predictions for all of these rows, but only the ones corresponding to real measurements will be 
# used in scoring.)

library(dplyr)
library(readr)
library(ggplot2)

data_dir <- "../input"
train <- read_csv(file.path(data_dir, "train.csv"))
test <- read_csv(file.path(data_dir, "test.csv"))
train$Usage <- "Train"
test$Usage <- "Test"

train_and_test <- bind_rows(train, test)

train_and_test$Date <- as.Date(train_and_test$Date)
locations_and_dates <- train_and_test %>% select(AddressNumberAndStreet, Longitude, Latitude, Date, Usage) %>% unique

theme_set(theme_gray(base_size = 20))
png(height=1920, width=1920)
ggplot(locations_and_dates) + 
  geom_point(aes(x=Date, y=AddressNumberAndStreet, color=Usage), size=1) +
  scale_x_date(breaks = "1 year")
dev.off()

SyntaxError: invalid syntax (<ipython-input-1-53a61e3be753>, line 15)

In [5]:
%ls

Project 3 starter code JB.ipynb  readme.md
kaggle-group-squads.md

In [14]:
train = pd.read_csv('../../../../train.csv')

,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,NumMosquitos,WnvPresent
0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9,1,0
1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9,1,0

In [ ]:
#41.7867837,-87.7550455

In [22]:
import numpy as np

vert_dist_mid = 41.7867838 - 41.954690
horz_dist_mid = -87.7550455 - (-87.800991)
dist_mid = np.sqrt(vert_dist_mid**2+horz_dist_mid**2)

dist_mid

0.17407895038944049

In [ ]:
vert_dist_mid = lat_mid - lat_trap
horz_dist_mid = long_mid - long_trap
train['dist_mid'] = sqrt(vert_dist_mid**2+horz_dist_mid**2)

In [25]:
lat_mid = 41.7867838
long_mid = -87.7550455

In [ ]:
def calc_dist()

In [30]:
df_distance['vert_dist_mid'] = lat_mid - df_distance['Latitude']
df_distance['horz_dist_mid'] = long_mid - df_distance['Longitude']
df_distance['mid'] = np.sqrt((df_distance['vert_dist_mid']**2)+(df_distance['horz_dist_mid']**2))
df_distance

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

       Trap   Latitude  Longitude       mid  vert_dist_mid  horz_dist_mid
0      T002  41.954690 -87.800991  0.174079      -0.167906       0.045946
1      T002  41.954690 -87.800991  0.174079      -0.167906       0.045946
2      T007  41.994991 -87.769279  0.208693      -0.208207       0.014234
3      T015  41.974089 -87.824812  0.199876      -0.187305       0.069767
4      T015  41.974089 -87.824812  0.199876      -0.187305       0.069767
5      T045  41.921600 -87.666455  0.161319      -0.134816      -0.088590
6      T046  41.891118 -87.654491  0.144903      -0.104334      -0.100554
7      T048  41.867108 -87.654224  0.128907      -0.080324      -0.100821
8      T048  41.867108 -87.654224  0.128907      -0.080324      -0.100821
9      T049  41.896282 -87.655232  0.148164      -0.109498      -0.099813
10     T050  41.919343 -87.694259  0.145832      -0.132559      -0.060786
11     T054  41.921965 -87.632085  0.182738      -0.135181      -0.122960
12     T054  41.921965 -87.632085  0.182738      -0.135181      -0.122960
13     T086  41.688324 -87.676709  0.125821       0.098460      -0.078336
14     T086  41.688324 -87.676709  0.125821       0.098460      -0.078336
15     T091  41.862292 -87.648860  0.130295      -0.075508      -0.106185
16     T094  41.720848 -87.666014  0.110789       0.065936      -0.089031
17     T096  41.731922 -87.677512  0.094980       0.054862      -0.077534
18     T096  41.731922 -87.677512  0.094980       0.054862      -0.077534
19     T129  41.891126 -87.611560  0.177413      -0.104342      -0.143485
20     T129  41.891126 -87.611560  0.177413      -0.104342      -0.143485
21     T143  41.999129 -87.795585  0.216180      -0.212345       0.040540
22     T148  42.017430 -87.687769  0.240258      -0.230646      -0.067277
23     T153  41.907645 -87.760886  0.121002      -0.120861       0.005841
24     T159  41.732984 -87.649642  0.118340       0.053800      -0.105403
25     T002  41.954690 -87.800991  0.174079      -0.167906       0.045946
26     T002  41.954690 -87.800991  0.174079      -0.167906       0.045946
27     T002  41.954690 -87.800991  0.174079      -0.167906       0.045946
28     T015  41.974089 -87.824812  0.199876      -0.187305       0.069767
29     T015  41.974089 -87.824812  0.199876      -0.187305       0.069767
...     ...        ...        ...       ...            ...            ...
10476  T102  41.750498 -87.605294  0.154085       0.036286      -0.149751
10477  T102  41.750498 -87.605294  0.154085       0.036286      -0.149751
10478  T102  41.750498 -87.605294  0.154085       0.036286      -0.149751
10479  T027  41.984809 -87.728492  0.199798      -0.198025      -0.026553
10480  T221  41.659112 -87.538693  0.251214       0.127672      -0.216352
10481  T221  41.659112 -87.538693  0.251214       0.127672      -0.216352
10482  T221  41.659112 -87.538693  0.251214       0.127672      -0.216352
10483  T009  41.992478 -87.862995  0.232300      -0.205694       0.107950
10484  T900  41.974689 -87.890615  0.231706      -0.187905       0.135570
10485  T900  41.974689 -87.890615  0.231706      -0.187905       0.135570
10486  T900  41.974689 -87.890615  0.231706      -0.187905       0.135570
10487  T900  41.974689 -87.890615  0.231706      -0.187905       0.135570
10488  T900  41.974689 -87.890615  0.231706      -0.187905       0.135570
10489  T900  41.974689 -87.890615  0.231706      -0.187905       0.135570
10490  T222  41.925198 -87.746381  0.138685      -0.138414      -0.008664
10491  T223  41.973845 -87.805059  0.193632      -0.187061       0.050014
10492  T223  41.973845 -87.805059  0.193632      -0.187061       0.050014
10493  T225  41.743402 -87.731435  0.049391       0.043382      -0.023610
10494  T227  41.728495 -87.600963  0.164739       0.058289      -0.154082
10495  T227  41.728495 -87.600963  0.164739       0.058289      -0.154082
10496  T224  41.947227 -87.671457  0.180912      -0.160443      -0.083589
10497  T226  41.793818 -87.654234  0.101057      -0.007034      -0.100811
10498  T230  41.904194 -87.756155  0.117415      -0.117410       0.001110
10499  T230  41.904194 -87.756155  0.117415      -0.117410       0.001110
10500  T228  41.951866 -87.725057  0.167784      -0.165082      -0.029989
10501  T035  41.763733 -87.742302  0.026339       0.023051      -0.012743
10502  T231  41.987280 -87.666066  0.219354      -0.200496      -0.088979
10503  T232  41.912563 -87.668055  0.152931      -0.125779      -0.086990
10504  T233  42.009876 -87.807277  0.229125      -0.223092       0.052232
10505  T235  41.776428 -87.627096  0.128368       0.010356      -0.127949

[10506 rows x 6 columns]

In [31]:
lat_ohare = 41.9837402
long_ohare = -87.977292

In [32]:
df_distance['vert_dist_ohare'] = lat_ohare - df_distance['Latitude']
df_distance['horz_dist_ohare'] = long_ohare - df_distance['Longitude']
df_distance['ohare'] = np.sqrt((df_distance['vert_dist_ohare']**2)+(df_distance['horz_dist_ohare']**2))
df_distance

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

,Trap,Latitude,Longitude,mid,vert_dist_mid,horz_dist_mid,vert_dist_ohare,horz_dist_ohare,ohare
0,T002,41.954690,-87.800991,0.174079,-0.167906,0.045946,0.029050,-0.176301,0.178678
1,T002,41.954690,-87.800991,0.174079,-0.167906,0.045946,0.029050,-0.176301,0.178678
2,T007,41.994991,-87.769279,0.208693,-0.208207,0.014234,-0.011251,-0.208013,0.208317
3,T015,41.974089,-87.824812,0.199876,-0.187305,0.069767,0.009651,-0.152480,0.152785
4,T015,41.974089,-87.824812,0.199876,-0.187305,0.069767,0.009651,-0.152480,0.152785
5,T045,41.921600,-87.666455,0.161319,-0.134816,-0.088590,0.062140,-0.310837,0.316987
6,T046,41.891118,-87.654491,0.144903,-0.104334,-0.100554,0.092622,-0.322801,0.335826
7,T048,41.867108,-87.654224,0.128907,-0.080324,-0.100821,0.116632,-0.323068,0.343476
8,T048,41.867108,-87.654224,0.128907,-0.080324,-0.100821,0.116632,-0.323068,0.343476
9,T049,41.896282,-87.655232,0.148164,-0.109498,-0.099813,0.087458,-0.322060,0.333724
10,T050,41.919343,-87.694259,0.145832,-0.132559,-0.060786,0.064397,-0.283033,0.290267
11,T054,41.921965,-87.632085,0.182738,-0.135181,-0.122960,0.061775,-0.345207,0.350691
12,T054,41.921965,-87.632085,0.182738,-0.135181,-0.122960,0.061775,-0.345207,0.350691
13,T086,41.688324,-87.676709,0.125821,0.098460,-0.078336,0.295416,-0.300583,0.421451
14,T086,41.688324,-87.676709,0.125821,0.098460,-0.078336,0.295416,-0.300583,0.421451
15,T091,41.862292,-87.648860,0.130295,-0.075508,-0.106185,0.121448,-0.328432,0.350167
16,T094,41.720848,-87.666014,0.110789,0.065936,-0.089031,0.262892,-0.311278,0.407439
17,T096,41.731922,-87.677512,0.094980,0.054862,-0.077534,0.251818,-0.299780,0.391510
18,T096,41.731922,-87.677512,0.094980,0.054862,-0.077534,0.251818,-0.299780,0.391510
19,T129,41.891126,-87.611560,0.177413,-0.104342,-0.143485,0.092614,-0.365732,0.377276
20,T129,41.891126,-87.611560,0.177413,-0.104342,-0.143485,0.092614,-0.365732,0.377276
21,T143,41.999129,-87.795585,0.216180,-0.212345,0.040540,-0.015389,-0.181707,0.182357
22,T148,42.017430,-87.687769,0.240258,-0.230646,-0.067277,-0.033690,-0.289523,0.291477
23,T153,41.907645,-87.760886,0.121002,-0.120861,0.005841,0.076095,-0.216406,0.229395
24,T159,41.732984,-87.649642,0.118340,0.053800,-0.105403,0.250756,-0.327650,0.412593
25,T002,41.954690,-87.800991,0.174079,-0.167906,0.045946,0.029050,-0.176301,0.178678
26,T002,41.954690,-87.800991,0.174079,-0.167906,0.045946,0.029050,-0.176301,0.178678
27,T002,41.954690,-87.800991,0.174079,-0.167906,0.045946,0.029050,-0.176301,0.178678
28,T015,41.974089,-87.824812,0.199876,-0.187305,0.069767,0.009651,-0.152480,0.152785
29,T015,41.974089,-87.824812,0.199876,-0.187305,0.069767,0.009651,-0.152480,0.152785
...,...,...,...,...,...,...,...,...,...
10476,T102,41.750498,-87.605294,0.154085,0.036286,-0.149751,0.233242,-0.371998,0.439072
10477,T102,41.750498,-87.605294,0.154085,0.036286,-0.149751,0.233242,-0.371998,0.439072
10478,T102,41.750498,-87.605294,0.154085,0.036286,-0.149751,0.233242,-0.371998,0.439072
10479,T027,41.984809,-87.728492,0.199798,-0.198025,-0.026553,-0.001069,-0.248800,0.248802
10480,T221,41.659112,-87.538693,0.251214,0.127672,-0.216352,0.324628,-0.438599,0.545667
10481,T221,41.659112,-87.538693,0.251214,0.127672,-0.216352,0.324628,-0.438599,0.545667
10482,T221,41.659112,-87.538693,0.251214,0.127672,-0.216352,0.324628,-0.438599,0.545667
10483,T009,41.992478,-87.862995,0.232300,-0.205694,0.107950,-0.008738,-0.114297,0.114631
10484,T900,41.974689,-87.890615,0.231706,-0.187905,0.135570,0.009051,-0.086677,0.087148
10485,T900,41.974689,-87.890615,0.231706,-0.187905,0.135570,0.009051,-0.086677,0.087148
10486,T900,41.974689,-87.890615,0.231706,-0.187905,0.135570,0.009051,-0.086677,0.087148
10487,T900,41.974689,-87.890615,0.231706,-0.187905,0.135570,0.009051,-0.086677,0.087148
10488,T900,41.974689,-87.890615,0.231706,-0.187905,0.135570,0.009051,-0.086677,0.087148
10489,T900,41.974689,-87.890615,0.231706,-0.187905,0.135570,0.009051,-0.086677,0.087148
10490,T222,41.925198,-87.746381,0.138685,-0.138414,-0.008664,0.058542,-0.230911,0.238216
10491,T223,41.973845,-87.805059,0.193632,-0.187061,0.050014,0.009895,-0.172233,0.172517
10492,T223,41.973845,-87.805059,0.193632,-0.187061,0.050014,0.009895,-0.172233,0.172517
10493,T225,41.743402,-87.731435,0.049391,0.043382,-0.023610,0.240338,-0.245857,0.343814
10494,T227,41.728495,-87.600963,0.164739,0.058289,-0.154082,0.255245,-0.376329,0.454724
10495,T227,41.728495,-87.600963,0.164739,0.058289,-0.154082,0.255245,-0.376329,0.454724
10496,T224,41.947227,-87.671457,0.180912,-0.160443,-0.083589,0.036513,-0.305835,0.308007
10497,T226,41.793818,-87.654234,0.101057,-0.007034,-0.100811,0.189922,-0.323058,0.374749
10498,T230,41.904194,-87.756155,0.117415,-0.117410,0.001110,0.079546,-0.221137,0.235009
10499,T230,41.904194,-87.756155,0.117415,-0.117410,0.001110,0.079546,-0.221137,0.235009
10500,T228,41.951866,-87.725057,0.167784,-0.165082,-0.029989,0.031874,-0.252235,0.254241
10501,T035,41.763733,-87.742302,0.026339,0.023051,-0.012743,0.220007,-0.234990,0.321906
10502,T231,41.987280,-87.666066,0.219354,-0.200496,-0.088979,-0.003540,-0.311226,0.311246
10503,T232,41.912563,-87.668055,0.152931,-0.125779,-0.086990,0.071177,-0.309237,0.317323
10504,T233,42.009876,-87.807277,0.229125,-0.223092,0.052232,-0.026136,-0.170015,0.172012
10505,T235,41.776428,-87.627096,0.128368,0.010356,-0.127949,0.207312,-0.350196,0.406959

In [24]:
df_distance = train[['Trap','Latitude','Longitude']]

In [18]:
train

,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy,NumMosquitos,WnvPresent
0,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0
1,2007-05-29,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0
2,2007-05-29,"6200 North Mandell Avenue, Chicago, IL 60646, USA",CULEX RESTUANS,62,N MANDELL AVE,T007,"6200 N MANDELL AVE, Chicago, IL",41.994991,-87.769279,9,1,0
3,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,1,0
4,2007-05-29,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,4,0
5,2007-05-29,"1500 West Webster Avenue, Chicago, IL 60614, USA",CULEX RESTUANS,15,W WEBSTER AVE,T045,"1500 W WEBSTER AVE, Chicago, IL",41.921600,-87.666455,8,2,0
6,2007-05-29,"2500 West Grand Avenue, Chicago, IL 60654, USA",CULEX RESTUANS,25,W GRAND AVE,T046,"2500 W GRAND AVE, Chicago, IL",41.891118,-87.654491,8,1,0
7,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX PIPIENS/RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,1,0
8,2007-05-29,"1100 Roosevelt Road, Chicago, IL 60608, USA",CULEX RESTUANS,11,W ROOSEVELT,T048,"1100 W ROOSEVELT, Chicago, IL",41.867108,-87.654224,8,2,0
9,2007-05-29,"1100 West Chicago Avenue, Chicago, IL 60642, USA",CULEX RESTUANS,11,W CHICAGO,T049,"1100 W CHICAGO, Chicago, IL",41.896282,-87.655232,8,1,0
10,2007-05-29,"2100 North Stave Street, Chicago, IL 60647, USA",CULEX PIPIENS/RESTUANS,21,N STAVE ST,T050,"2100 N STAVE ST, Chicago, IL",41.919343,-87.694259,8,1,0
11,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX PIPIENS/RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,8,2,0
12,2007-05-29,"2200 North Cannon Drive, Chicago, IL 60614, USA",CULEX RESTUANS,22,N CANNON DR,T054,"2200 N CANNON DR, Chicago, IL",41.921965,-87.632085,8,3,0
13,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX PIPIENS/RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,8,1,0
14,2007-05-29,"2200 West 113th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 113TH ST,T086,"2200 W 113TH ST, Chicago, IL",41.688324,-87.676709,8,1,0
15,2007-05-29,"1100 South Peoria Street, Chicago, IL 60608, USA",CULEX RESTUANS,11,S PEORIA ST,T091,"1100 S PEORIA ST, Chicago, IL",41.862292,-87.648860,8,1,0
16,2007-05-29,"1700 West 95th Street, Chicago, IL 60643, USA",CULEX RESTUANS,17,W 95TH ST,T094,"1700 W 95TH ST, Chicago, IL",41.720848,-87.666014,9,3,0
17,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX RESTUANS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,5,0
18,2007-05-29,"2200 West 89th Street, Chicago, IL 60643, USA",CULEX PIPIENS,22,W 89TH ST,T096,"2200 W 89TH ST, Chicago, IL",41.731922,-87.677512,8,1,0
19,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX PIPIENS/RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,5,1,0
20,2007-05-29,"North Streeter Drive, Chicago, IL 60611, USA",CULEX RESTUANS,53,N STREETER DR,T129,"5300 N STREETER DR, Chicago, IL",41.891126,-87.611560,5,2,0
21,2007-05-29,"6500 North Oak Park Avenue, Chicago, IL 60631,...",CULEX PIPIENS/RESTUANS,65,N OAK PARK AVE,T143,"6500 N OAK PARK AVE, Chicago, IL",41.999129,-87.795585,8,1,0
22,2007-05-29,"7500 North Oakley Avenue, Chicago, IL 60645, USA",CULEX PIPIENS/RESTUANS,75,N OAKLEY AVE,T148,"7500 N OAKLEY AVE, Chicago, IL",42.017430,-87.687769,8,1,0
23,2007-05-29,"1500 North Long Avenue, Chicago, IL 60651, USA",CULEX RESTUANS,15,N LONG AVE,T153,"1500 N LONG AVE, Chicago, IL",41.907645,-87.760886,8,1,0
24,2007-05-29,"8900 South Carpenter Street, Chicago, IL 60620...",CULEX RESTUANS,89,S CARPENTER ST,T159,"8900 S CARPENTER ST, Chicago, IL",41.732984,-87.649642,8,1,0
25,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,3,0
26,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,5,0
27,2007-06-05,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.954690,-87.800991,9,1,0
28,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX PIPIENS/RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,1,0
29,2007-06-05,"7900 West Foster Avenue, Chicago, IL 60656, USA",CULEX RESTUANS,79,W FOSTER AVE,T015,"7900 W FOSTER AVE, Chicago, IL",41.974089,-87.824812,8,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10476,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,2,0
10477,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX RESTUANS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,1,0
10478,2013-09-26,"South Cottage Grove Avenue, Chicago, IL, USA",CULEX PIPIENS,10,S COTTAGE GROVE,T102,"1000 S COTTAGE GROVE, Chicago, IL",41.750498,-87.605294,5,1,0
10479,2013-09-26,"5800 North Pulaski Road, Chicago, IL 60646, USA",CULEX PIPIENS,58,N PULASKI RD,T027,"5800 N PULASKI RD, Chicago, IL",41.984809,-87.728492,8,5,0
10480,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS/RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,5,0
10481,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX RESTUANS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,5,0
10482,2013-09-26,"4000 East 130th Street, Chicago, IL 60633, USA",CULEX PIPIENS,40,E 130TH ST,T221,"4000 E 130TH ST, Chicago, IL",41.659112,-87.538693,8,4,0
10483,2013-09-26,"9100 West Higgins Road, Rosemont, IL 60018, USA",CULEX RESTUANS,91,W HIGGINS RD,T009,"9100 W HIGGINS RD, Chicago, IL",41.992478,-87.862995,8,1,0
10484,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS/RESTUANS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,39,1
10485,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS/RESTUANS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,4,0
10486,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,16,0
10487,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,9,0
10488,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,11,0
10489,2013-09-26,"ORD Terminal 5, O'Hare International Airport, ...",CULEX PIPIENS,10,W OHARE AIRPORT,T900,"1000 W OHARE AIRPORT, Chicago, IL",41.974689,-87.890615,9,1,0
10490,2013-09-26,"4800 West Montana Street, Chicago, IL 60639, USA",CULEX PIPIENS/RESTUANS,48,W MONTANA ST,T222,"4800 W MONTANA ST, Chicago, IL",41.925198,-87.746381,8,1,0
10491,2013-09-26,"5100 North Mont Clare Avenue, Chicago, IL 6065...",CULEX PIPIENS/RESTUANS,51,N MONT CLARE AVE,T223,"5100 N MONT CLARE AVE, Chicago, IL",41.973845,-87.805059,9,11,0
10492,2013-09-26,"5100 North Mont Clare Avenue, Chicago, IL 6065...",CULEX PIPIENS,51,N MONT CLARE AVE,T223,"5100 N MONT CLARE AVE, Chicago, IL",41.973845,-87.805059,9,1,0
10493,2013-09-26,"8200 South Kostner Avenue, Chicago, IL 60652, USA",CULEX PIPIENS/RESTUANS,82,S KOSTNER AVE,T225,"8200 S KOSTNER AVE, Chicago, IL",41.743402,-87.731435,8,3,0
10494,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,5,7,0
10495,2013-09-26,"East 91st Place, Chicago, IL, USA",CULEX PIPIENS,65,E 91ST PL,T227,"6500 E 91ST PL, Chicago, IL",41.728495,-87.600963,5,1,0
10496,2013-09-26,"1700 West Addison Street, Chicago, IL 60613, USA",CULEX PIPIENS/RESTUANS,17,W ADDISON ST,T224,"1700 W ADDISON ST, Chicago, IL",41.947227,-87.671457,9,3,0
10497,2013-09-26,"West Garfield Boulevard, Chicago, IL, USA",CULEX PIPIENS/RESTUANS,90,W GARFIELD BLVD,T226,"9000 W GARFIELD BLVD, Chicago, IL",41.793818,-87.654234,5,8,0
10498,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS/RESTUANS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,9,13,0
10499,2013-09-26,"1300 North Laramie Avenue, Chicago, IL 60651, USA",CULEX PIPIENS,13,N LARAMIE AVE,T230,"1300 N LARAMIE AVE, Chicago, IL",41.904194,-87.756155,9,5,0
10500,2013-09-26,"3900 North Springfield Avenue, Chicago, IL 606...",CULEX PIPIENS/RESTUANS,39,N SPRINGFIELD AVE,T228,"3900 N SPRINGFIELD AVE, Chicago, IL",41.951866,-87.725057,8,3,0
10501,2013-09-26,"5100 West 72nd Street, Chicago, IL 60638, USA",CULEX PIPIENS/RESTUANS,51,W 72ND ST,T035,"5100 W 72ND ST, Chicago, IL",41.763733,-87.742302,8,6,1
10502,2013-09-26,"5800 North Ridge Avenue, Chicago, IL 60660, USA",CULEX PIPIENS/RESTUANS,58,N RIDGE AVE,T231,"5800 N RIDGE AVE, Chicago, IL",41.987280,-87.666066,8,5,0
10503,2013-09-26,"1700 North Ashland Avenue, Chicago, IL 60622, USA",CULEX PIPIENS/RESTUANS,17,N ASHLAND AVE,T232,"1700 N ASHLAND AVE, Chicago, IL",41.912563,-87.668055,9,1,0
10504,2013-09-26,"7100 North Harlem Avenue, Chicago, IL 60631, USA",CULEX PIPIENS/RESTUANS,71,N HARLEM AVE,T233,"7100 N HARLEM AVE, Chicago, IL",42.009876,-87.807277,9,5,0
10505,2013-09-26,"4200 West 65th Street, Chicago, IL 60621, USA",CULEX PIPIENS/RESTUANS,42,W 65TH ST,T235,"4200 W 65TH ST, Chicago, IL",41.776428,-87.627096,8,1,0

In [21]:
weather

,Station,Date,Tmax,Tmin,Tavg,Depart,DewPoint,WetBulb,Heat,Cool,...,CodeSum,Depth,Water1,SnowFall,PrecipTotal,StnPressure,SeaLevel,ResultSpeed,ResultDir,AvgSpeed
0,1,2007-05-01,83,50,67,14,51,56,0,2,...,,0,M,0.0,0.00,29.10,29.82,1.7,27,9.2
1,2,2007-05-01,84,52,68,M,51,57,0,3,...,,M,M,M,0.00,29.18,29.82,2.7,25,9.6
2,1,2007-05-02,59,42,51,-3,42,47,14,0,...,BR,0,M,0.0,0.00,29.38,30.09,13.0,4,13.4
3,2,2007-05-02,60,43,52,M,42,47,13,0,...,BR HZ,M,M,M,0.00,29.44,30.08,13.3,2,13.4
4,1,2007-05-03,66,46,56,2,40,48,9,0,...,,0,M,0.0,0.00,29.39,30.12,11.7,7,11.9
5,2,2007-05-03,67,48,58,M,40,50,7,0,...,HZ,M,M,M,0.00,29.46,30.12,12.9,6,13.2
6,1,2007-05-04,66,49,58,4,41,50,7,0,...,RA,0,M,0.0,T,29.31,30.05,10.4,8,10.8
7,2,2007-05-04,78,51,M,M,42,50,M,M,...,,M,M,M,0.00,29.36,30.04,10.1,7,10.4
8,1,2007-05-05,66,53,60,5,38,49,5,0,...,,0,M,0.0,T,29.40,30.10,11.7,7,12.0
9,2,2007-05-05,66,54,60,M,39,50,5,0,...,,M,M,M,T,29.46,30.09,11.2,7,11.5
10,1,2007-05-06,68,49,59,4,30,46,6,0,...,,0,M,0.0,0.00,29.57,30.29,14.4,11,15.0
11,2,2007-05-06,68,52,60,M,30,46,5,0,...,,M,M,M,0.00,29.62,30.28,13.8,10,14.5
12,1,2007-05-07,83,47,65,10,41,54,0,0,...,RA,0,M,0.0,T,29.38,30.12,8.6,18,10.5
13,2,2007-05-07,84,50,67,M,39,53,0,2,...,,M,M,M,0.00,29.44,30.12,8.5,17,9.9
14,1,2007-05-08,82,54,68,12,58,62,0,3,...,BR,0,M,0.0,0.00,29.29,30.03,2.7,11,5.8
15,2,2007-05-08,80,60,70,M,57,63,0,5,...,HZ,M,M,M,T,29.36,30.02,2.5,8,5.4
16,1,2007-05-09,77,61,69,13,59,63,0,4,...,BR HZ,0,M,0.0,0.13,29.21,29.94,3.9,9,6.2
17,2,2007-05-09,76,63,70,M,60,63,0,5,...,BR HZ,M,M,M,0.02,29.28,29.93,3.9,7,5.9
18,1,2007-05-10,84,56,70,14,52,60,0,5,...,BR,0,M,0.0,0.00,29.20,29.92,0.7,17,4.1
19,2,2007-05-10,83,59,71,M,52,61,0,6,...,BR HZ,M,M,M,0.00,29.26,29.91,2.0,9,3.9
20,1,2007-05-11,70,51,61,4,42,51,4,0,...,,0,M,0.0,0.00,29.33,30.04,11.3,3,12.9
21,2,2007-05-11,73,49,61,M,44,51,4,0,...,,M,M,M,0.00,29.39,30.03,11.7,36,12.8
22,1,2007-05-12,64,46,55,-2,36,46,10,0,...,,0,M,0.0,0.00,29.49,30.20,12.4,3,12.9
23,2,2007-05-12,65,47,56,M,37,46,9,0,...,,M,M,M,0.00,29.54,30.19,12.7,1,13.0
24,1,2007-05-13,69,43,56,-2,33,46,9,0,...,,0,M,0.0,0.00,29.49,30.24,6.6,14,8.1
25,2,2007-05-13,69,44,57,M,32,46,8,0,...,,M,M,M,0.00,29.55,30.24,6.4,11,7.6
26,1,2007-05-14,90,56,73,15,47,59,0,8,...,,0,M,0.0,0.00,29.23,29.97,16.9,21,17.3
27,2,2007-05-14,90,54,72,M,45,58,0,7,...,,M,M,M,0.00,29.31,29.98,14.1,21,14.6
28,1,2007-05-15,80,57,69,11,56,61,0,4,...,RA BR,0,M,0.0,0.38,29.13,29.84,8.1,27,12.3
29,2,2007-05-15,82,56,69,M,56,61,0,4,...,TSRA RA BR,M,M,M,0.60,29.19,29.83,8.1,25,10.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,1,2014-10-17,62,48,55,3,46,50,10,0,...,,0,M,0.0,T,28.99,29.69,11.1,29,13.2
2915,2,2014-10-17,63,49,56,M,48,52,9,0,...,,M,M,M,0.01,29.05,29.69,10.7,28,12.7
2916,1,2014-10-18,50,36,43,-8,38,42,22,0,...,RA DZ,0,M,0.0,0.01,29.39,30.08,8.2,34,9.2
2917,2,2014-10-18,52,39,46,M,40,44,19,0,...,RA,M,M,M,0.02,29.44,30.08,7.6,34,8.7
2918,1,2014-10-19,54,33,44,-7,38,43,21,0,...,,0,M,0.0,0.00,29.31,30.07,7.8,21,8.2
2919,2,2014-10-19,57,36,47,M,40,44,18,0,...,,M,M,M,0.00,29.39,30.09,8.8,21,9.0
2920,1,2014-10-20,65,46,56,6,44,49,9,0,...,,0,M,0.0,0.01,29.17,29.90,4.7,32,9.3
2921,2,2014-10-20,66,50,58,M,46,51,7,0,...,,M,M,M,0.00,29.23,29.90,4.9,32,9.1
2922,1,2014-10-21,53,45,49,-1,39,44,16,0,...,,0,M,0.0,0.00,29.46,30.16,10.8,1,11.4
2923,2,2014-10-21,54,49,52,M,41,46,13,0,...,,M,M,M,0.00,29.51,30.15,11.0,36,11.6
2924,1,2014-10-22,56,35,46,-4,38,43,19,0,...,,0,M,0.0,0.00,29.56,30.30,2.9,8,4.8
2925,2,2014-10-22,56,43,50,M,38,44,15,0,...,,M,M,M,0.00,29.62,30.30,3.0,11,5.1
2926,1,2014-10-23,59,36,48,-1,40,45,17,0,...,BR,0,M,0.0,0.00,29.39,30.15,7.5,19,7.8
2927,2,2014-10-23,62,41,52,M,41,47,13,0,...,BR,M,M,M,T,29.46,30.16,7.9,19,8.4
2928,1,2014-10-24,67,52,60,11,46,52,5,0,...,,0,M,0.0,0.00,29.25,30.00,4.4,22,5.8
2929,2,2014-10-24,68,54,61,M,48,53,4,0,...,,M,M,M,0.00,29.31,30.00,4.9,22,5.8
2930,1,2014-10-25,72,49,61,13,40,51,4,0,...,BR,0,M,0.0,0.00,29.21,29.93,10.4,29,10.9
2931,2,2014-10-25,75,52,64,M,41,52,1,0,...,BR HZ,M,M,M,0.00,29.27,29.92,9.7,28,10.4
2932,1,2014-10-26,64,42,53,5,32,44,12,0,...,,0,M,0.0,0.00,29.21,29.95,0.9,5,5.8
2933,2,2014-10-26,66,44,55,M,33,45,10,0,...,,M,M,M,0.00,29.28,29.95,1.6,11,5.4
2934,1,2014-10-27,77,51,64,16,51,58,1,0,...,,0,M,0.0,0.00,28.92,29.66,12.0,19,12.9
2935,2,2014-10-27,79,54,67,M,52,59,0,2,...,RA,M,M,M,0.02,29.00,29.67,12.7,19,13.6
2936,1,2014-10-28,68,45,57,10,38,47,8,0,...,,0,M,0.0,T,29.15,29.85,14.8,26,15.6
2937,2,2014-10-28,66,48,57,M,40,48,8,0,...,RA,M,M,M,0.03,29.23,29.85,14.0,26,14.6
2938,1,2014-10-29,49,36,43,-4,32,40,22,0,...,,0,M,0.0,0.00,29.36,30.06,9.5,29,9.9
2939,2,2014-10-29,49,40,45,M,34,42,20,0,...,,M,M,M,0.00,29.42,30.07,8.5,29,9.0
2940,1,2014-10-30,51,32,42,-4,34,40,23,0,...,,0,M,0.0,0.00,29.34,30.09,5.1,24,5.5
2941,2,2014-10-30,53,37,45,M,35,42,20,0,...,RA,M,M,M,T,29.41,30.10,5.9,23,6.5
2942,1,2014-10-31,47,33,40,-6,25,33,25,0,...,RA SN,0,M,0.1,0.03,29.49,30.20,22.6,34,22.9
2943,2,2014-10-31,49,34,42,M,29,36,23,0,...,RA SN BR,M,M,M,0.04,29.54,30.20,21.7,34,22.6

In [17]:
test = pd.read_csv('../../../../test.csv')

test.head(2)

,Id,Date,Address,Species,Block,Street,Trap,AddressNumberAndStreet,Latitude,Longitude,AddressAccuracy
0,1,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX PIPIENS/RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9
1,2,2008-06-11,"4100 North Oak Park Avenue, Chicago, IL 60634,...",CULEX RESTUANS,41,N OAK PARK AVE,T002,"4100 N OAK PARK AVE, Chicago, IL",41.95469,-87.800991,9

In [8]:
import pandas as pd
import numpy as np
from sklearn import ensemble, preprocessing

# Load dataset 
train = pd.read_csv('../../../../train.csv')
test = pd.read_csv('../../../../test.csv')
sample = pd.read_csv('../../../../samplesubmission.csv')
weather = pd.read_csv('../../../../weather.csv')

# Get labels
labels = train.WnvPresent.values

# Not using codesum for this benchmark
weather = weather.drop('CodeSum', axis=1)

# Split station 1 and 2 and join horizontally
weather_stn1 = weather[weather['Station']==1]
weather_stn2 = weather[weather['Station']==2]
weather_stn1 = weather_stn1.drop('Station', axis=1)
weather_stn2 = weather_stn2.drop('Station', axis=1)
weather = weather_stn1.merge(weather_stn2, on='Date')

# replace some missing values and T with -1
weather = weather.replace('M', -1)
weather = weather.replace('-', -1)
weather = weather.replace('T', -1)
weather = weather.replace(' T', -1)
weather = weather.replace('  T', -1)

# Functions to extract month and day from dataset
# You can also use parse_dates of Pandas.
def create_month(x):
    return x.split('-')[1]

def create_day(x):
    return x.split('-')[2]

train['month'] = train.Date.apply(create_month)
train['day'] = train.Date.apply(create_day)
test['month'] = test.Date.apply(create_month)
test['day'] = test.Date.apply(create_day)

# Add integer latitude/longitude columns
train['Lat_int'] = train.Latitude.apply(int)
train['Long_int'] = train.Longitude.apply(int)
test['Lat_int'] = test.Latitude.apply(int)
test['Long_int'] = test.Longitude.apply(int)

# drop address columns
train = train.drop(['Address', 'AddressNumberAndStreet','WnvPresent', 'NumMosquitos'], axis = 1)
test = test.drop(['Id', 'Address', 'AddressNumberAndStreet'], axis = 1)

# Merge with weather data
train = train.merge(weather, on='Date')
test = test.merge(weather, on='Date')
train = train.drop(['Date'], axis = 1)
test = test.drop(['Date'], axis = 1)

# Convert categorical data to numbers
lbl = preprocessing.LabelEncoder()
lbl.fit(list(train['Species'].values) + list(test['Species'].values))
train['Species'] = lbl.transform(train['Species'].values)
test['Species'] = lbl.transform(test['Species'].values)

lbl.fit(list(train['Street'].values) + list(test['Street'].values))
train['Street'] = lbl.transform(train['Street'].values)
test['Street'] = lbl.transform(test['Street'].values)

lbl.fit(list(train['Trap'].values) + list(test['Trap'].values))
train['Trap'] = lbl.transform(train['Trap'].values)
test['Trap'] = lbl.transform(test['Trap'].values)

# drop columns with -1s
train = train.ix[:,(train != -1).any(axis=0)]
test = test.ix[:,(test != -1).any(axis=0)]

# Random Forest Classifier 
clf = ensemble.RandomForestClassifier(n_jobs=-1, n_estimators=1000, min_samples_split=1)
clf.fit(train, labels)

# create predictions and submission file
predictions = clf.predict_proba(test)[:,1]
sample['WnvPresent'] = predictions
sample.to_csv('beat_the_benchmark.csv', index=False)

ValueError: Length of values does not match length of index